name: Run Supabase Edge Function

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  run-edge-function:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Supabase Edge Function Every 30s
        run: |
          for i in {1..10}; do
            curl -X POST "https://lzmdwphknysxryhxgokq.functions.supabase.co/PumpFunc" \
                 -H "Authorization: Bearer ${{ secrets.SUPABASE_SECRET_KEY }}" \
                 -H "Content-Type: application/json"
            echo "Supabase Edge Function executed at $(date)"
            sleep 30  # Wait for 30 seconds before next request
          done
