name: Run Supabase Edge Function Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  call_supabase_function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function Every 30 Seconds (Loop for 5 Min)
        run: |
          for i in {1..10}
          do
            curl -X POST "https://lzmdwphknysxryhxgokq.functions.supabase.co/PumpFunc" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.SUPABASE_SECRET }}" \
              --data "$(echo '{}' | jq -c .)"
            sleep 30
          done
